energy <- read.table("household_power_consumption.txt", header=TRUE, sep=";", na.strings = "?")
energy$DateTime <- as.POSIXct(paste(energy$Date, energy$Time), format="%d/%m/%Y %H:%M:%S")
subset_energy <- subset(energy, energy$DateTime>="2007-02-01" & energy$DateTime<"2007-02-03")
png("plot3.png", width = 480, height = 480, units="px")
plot(subset_energy$DateTime,subset_energy$Sub_metering_1, type="n", xlab="", ylab="Energy sub metering")
lines(subset_energy$DateTime,subset_energy$Sub_metering_1, type = "l", col="BLACK")
lines(subset_energy$DateTime,subset_energy$Sub_metering_2, type = "l", col="RED")
lines(subset_energy$DateTime,subset_energy$Sub_metering_3, type = "l", col="BLUE")
legend("topright", lty=1, col=c("black", "red", "blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()