energy <- read.table("household_power_consumption.txt", header=TRUE, sep=";", na.strings = "?")
energy$DateTime <- as.POSIXct(paste(energy$Date, energy$Time), format="%d/%m/%Y %H:%M:%S")
subset_energy <- subset(energy, energy$DateTime>="2007-02-01" & energy$DateTime<"2007-02-03")
png("plot2.png", width = 480, height = 480, units="px")
plot(subset_energy$DateTime, subset_energy$Global_active_power, type="n", xlab="", ylab="Global Active Power (kilowatts)")
lines(subset_energy$DateTime,subset_energy$Global_active_power, type = "l")
dev.off()